#!/usr/bin/env python3
"""
OSM-TO-SCAD — print any city block on Earth.

Downloads real building footprints from OpenStreetMap (via the Overpass
API) and writes an OpenSCAD file where every building is extruded to its
real height. Open the result in OpenSCAD, press F6, export STL, print
your neighborhood.

Uses only the Python standard library — nothing to install.

Usage (Dad may need to help find the bounding box):
  1. Go to https://www.openstreetmap.org, navigate to your spot,
     click "Export" — it shows the four bbox numbers.
  2. Run:
     python3 osm-to-scad.py --bbox SOUTH,WEST,NORTH,EAST > myblock.scad
     e.g. a slice of Lower Manhattan:
     python3 osm-to-scad.py --bbox 40.7065,-74.0135,40.7105,-74.0085 > fidi.scad
  3. Open myblock.scad in OpenSCAD, F6, export STL, slice, print.

Notes:
  * Keep the box SMALL (a few blocks). A whole city = a huge file and
    a sad printer.
  * --scale 2000 means 1:2000 (1 mm = 2 m). Bigger number = smaller model.
  * Buildings with no height data get --default-levels floors.
"""

import argparse
import json
import math
import sys
import urllib.parse
import urllib.request

OVERPASS = "https://overpass-api.de/api/interpreter"
FLOOR_M = 3.2  # meters per building level, a common estimate


def fetch(bbox):
    south, west, north, east = bbox
    query = f"""
    [out:json][timeout:60];
    (way["building"]({south},{west},{north},{east}););
    out body; >; out skel qt;
    """
    req = urllib.request.Request(
        OVERPASS,
        data=urllib.parse.urlencode({"data": query}).encode(),
        headers={"User-Agent": "family-3d-printing-project/1.0"},
    )
    with urllib.request.urlopen(req, timeout=90) as r:
        return json.load(r)


def building_height_m(tags):
    """Real height if OSM knows it, else floors * 3.2 m."""
    for key in ("height", "building:height"):
        if key in tags:
            try:
                return float(str(tags[key]).replace("m", "").strip())
            except ValueError:
                pass
    for key in ("building:levels", "levels"):
        if key in tags:
            try:
                return float(tags[key]) * FLOOR_M
            except ValueError:
                pass
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bbox", required=True,
                    help="south,west,north,east (from openstreetmap.org Export)")
    ap.add_argument("--scale", type=float, default=2000,
                    help="model scale denominator, default 2000 (=1:2000)")
    ap.add_argument("--default-levels", type=float, default=3,
                    help="floors to assume when OSM has no height data")
    ap.add_argument("--base", type=float, default=2,
                    help="base plate thickness in mm (0 = no plate)")
    args = ap.parse_args()

    bbox = [float(x) for x in args.bbox.split(",")]
    south, west, north, east = bbox

    print("Downloading from OpenStreetMap...", file=sys.stderr)
    data = fetch(bbox)

    nodes = {e["id"]: (e["lon"], e["lat"])
             for e in data["elements"] if e["type"] == "node"}
    ways = [e for e in data["elements"]
            if e["type"] == "way" and "nodes" in e]

    # lon/lat degrees -> millimeters at model scale
    lat0 = math.radians((south + north) / 2)
    m_per_deg_lat = 111_320.0
    m_per_deg_lon = 111_320.0 * math.cos(lat0)

    def to_mm(lon, lat):
        x_m = (lon - west) * m_per_deg_lon
        y_m = (lat - south) * m_per_deg_lat
        return (x_m * 1000 / args.scale, y_m * 1000 / args.scale)

    plate_w, plate_d = to_mm(east, north)

    out = sys.stdout
    out.write("// Generated by osm-to-scad.py — real OpenStreetMap data!\n")
    out.write(f"// bbox: {args.bbox}   scale 1:{args.scale:g}\n")
    out.write(f"// plate: {plate_w:.0f} x {plate_d:.0f} mm — check it fits!\n\n")
    if args.base > 0:
        out.write(f"cube([{plate_w:.2f}, {plate_d:.2f}, {args.base}]);\n\n")

    count = skipped = 0
    for way in ways:
        pts = [nodes[n] for n in way["nodes"] if n in nodes]
        if len(pts) < 4 or pts[0] != pts[-1]:
            skipped += 1
            continue
        tags = way.get("tags", {})
        h_m = building_height_m(tags)
        if h_m is None:
            h_m = args.default_levels * FLOOR_M
        h_mm = max(0.6, h_m * 1000 / args.scale)

        poly = [to_mm(lon, lat) for lon, lat in pts[:-1]]
        pts_str = ", ".join(f"[{x:.2f},{y:.2f}]" for x, y in poly)
        name = tags.get("name", "")
        out.write(f"// {name}\n" if name else "")
        out.write(f"translate([0,0,{args.base}]) "
                  f"linear_extrude({h_mm:.2f}) polygon([{pts_str}]);\n")
        count += 1

    print(f"Done: {count} buildings ({skipped} skipped), "
          f"plate {plate_w:.0f} x {plate_d:.0f} mm.", file=sys.stderr)
    if plate_w > 300 or plate_d > 300:
        print("WARNING: bigger than the H2C plate (~330x320) — "
              "shrink the bbox or raise --scale.", file=sys.stderr)


if __name__ == "__main__":
    main()
