// ============================================================
// SKYLINE GENERATOR — a procedural city, one number at a time
// ============================================================
// "Procedural" means the skyline is GENERATED by rules + random
// numbers instead of modeled by hand. This file builds a strip
// of N buildings (like the NYC skyline we printed, but this one
// is invented fresh every time).
//
// THE BIG IDEA — reproducible randomness:
// rands() gives "random" numbers, but they're really PSEUDO-
// random: the seed number decides the whole sequence. Same seed
// = the exact same city, every single render, on any computer.
// Change the seed = a brand new city. That's how Minecraft
// worlds, roguelike games, and real CAD tools do "random but
// repeatable" — you can share a city just by sharing its seed.
//
// Print: flat on the plate, NO supports — every setback tier
// sits fully on the tier below it, and the window bands are
// shallow recesses that bridge fine. ~2-4 hrs depending on size.
// Multi-color: windows are recessed, so height-range or face
// painting in Bambu Studio picks them out easily.
// ============================================================

// ------------ CHANGE THESE ------------
n_buildings = 9;     // how many towers in the strip?
seed        = 3;     // the city's DNA — change it, get a new city!
max_h       = 70;    // tallest possible building (mm)
base_len    = 190;   // length of the base bar (mm) — fits the plate
// ---------------------------------------

// ---- strip dimensions ----
bar_d      = 24;    // base bar depth
bar_h      = 3;     // base bar thickness
gap        = 2;     // breathing room between towers
end_margin = 3;     // bare bar at each end
floor_h    = 4;     // one "story" — heights snap to whole floors

$fn = 48;

// ---- the dice rolls (one list per building property) ----
// rands(low, high, count, seed) = `count` numbers between low
// and high. Different seeds for each property (seed+1, seed+2...)
// so width and height rolls don't copy each other.
raw_w  = rands(0.6, 1.6, n_buildings, seed);      // relative widths
raw_h  = rands(0.30, 1.0, n_buildings, seed + 1); // height fractions
raw_d  = rands(0.55, 1.0, n_buildings, seed + 2); // depth fractions
raw_r  = rands(0, 3, n_buildings, seed + 3);      // roof picker

// add up a list (OpenSCAD has no built-in sum, so we make one:
// "the sum from item i onward is item i plus the sum of the rest")
function sum(v, i = 0) = i >= len(v) ? 0 : v[i] + sum(v, i + 1);
// sum of just the first n items — used to stack widths left to right
function sum_to(v, n) = n <= 0 ? 0 : v[n-1] + sum_to(v, n - 1);

// scale the relative widths so all towers + gaps exactly fill the bar
usable = base_len - 2*end_margin - gap * (n_buildings - 1);
widths = [for (r = raw_w) r / sum(raw_w) * usable];

function bldg_x(i) = end_margin + sum_to(widths, i) + gap * i;      // left edge
function bldg_h(i) = max(2, floor(raw_h[i] * max_h / floor_h)) * floor_h;
function bldg_d(i) = raw_d[i] * (bar_d - 4);
function roof_of(i) = min(2, floor(raw_r[i]));  // 0 flat, 1 setback, 2 spire

// ---- one tower: a box with recessed window bands ----
// One shallow horizontal groove per floor, front and back. At
// skyline scale, bands read as rows of lit windows.
module tower(w, d, h) {
    margin = 1.2;   // solid wall left/right of the bands
    difference() {
        cube([w, d, h]);
        for (z = [floor_h : floor_h : h - floor_h]) {
            translate([margin, -0.05, z])         // front face
                cube([w - 2*margin, 0.7, 1.4]);
            translate([margin, d - 0.65, z])      // back face
                cube([w - 2*margin, 0.7, 1.4]);
        }
    }
}

// ---- one building: tower + its rolled roof style ----
module building(w, d, h, roof) {
    tower(w, d, h);

    if (roof == 0) {
        // flat roof with a parapet (the little wall around the edge)
        translate([0, 0, h]) difference() {
            cube([w, d, 1.2]);
            translate([1, 1, -0.1]) cube([w - 2, d - 2, 1.4]);
        }
    }
    if (roof == 1) {
        // setback tiers, 1916-zoning-law style — each tier is
        // centered on the one below, so it needs no supports
        h2 = max(floor_h, floor(h * 0.30 / floor_h) * floor_h);
        translate([w * 0.175, d * 0.175, h])
            tower(w * 0.65, d * 0.65, h2);
        translate([w * 0.325, d * 0.325, h + h2])
            tower(w * 0.35, d * 0.35, floor_h);
    }
    if (roof == 2) {
        // radio-mast spire, Empire State style
        translate([w/2, d/2, h])
            cylinder(h = min(10, h * 0.35), r1 = min(w, d) * 0.15, r2 = 0.5);
    }
}

// ---- build the city ----
cube([base_len, bar_d, bar_h]);   // the base bar everything stands on

for (i = [0 : n_buildings - 1])
    translate([bldg_x(i), (bar_d - bldg_d(i)) / 2, bar_h])
        building(widths[i], bldg_d(i), bldg_h(i), roof_of(i));

// IDEAS TO TRY (or ask Claude):
//  - roll seeds until you find a skyline you love, then print it
//    and write the seed on the back — it's the city's name
//  - add a 4th roof style (dome? pyramid? water tower?) and
//    change roof_of() to pick from 4
//  - make a matching back row: a second strip with max_h * 0.6
//    printed behind this one for depth
//  - stand it up: add a wider foot so it displays vertically on
//    a shelf like a real skyline silhouette
