#!/usr/bin/env python3
"""
STREETS-TO-SCAD — print your neighborhood's street map.

Downloads the real street network from OpenStreetMap (Overpass API) and
writes an OpenSCAD file where every road is a raised line on a base
plate — a printable street-map tile of anywhere on Earth. Big roads
print wider than side streets, just like a real map.

Uses only the Python standard library — nothing to install.

Usage:
  1. Get a bbox from https://www.openstreetmap.org -> Export.
     Keep it small — a neighborhood, not a whole city.
  2. python3 streets-to-scad.py --bbox 40.7065,-74.0135,40.7105,-74.0085 \
         > streets.scad
  3. OpenSCAD -> F6 -> export STL -> print.

Multi-color tip: roads sit exactly `road_raise` above the plate, so
Bambu Studio height-range painting colors every street in one click.
Great gift: your grandparents' neighborhood as a coaster.
"""

import argparse
import json
import math
import sys
import urllib.parse
import urllib.request

OVERPASS = "https://overpass-api.de/api/interpreter"

# printed half-width (relative units, scaled later) per road class
ROAD_CLASSES = {
    "motorway": 5.0, "trunk": 4.5, "primary": 4.0, "secondary": 3.2,
    "tertiary": 2.6, "residential": 2.0, "unclassified": 2.0,
    "living_street": 1.8, "service": 1.2, "pedestrian": 1.4,
    "footway": 0.8, "path": 0.8, "cycleway": 0.9,
}


def fetch(bbox):
    south, west, north, east = bbox
    kinds = "|".join(ROAD_CLASSES)
    query = f"""
    [out:json][timeout:60];
    (way["highway"~"^({kinds})$"]({south},{west},{north},{east}););
    out geom;
    """
    req = urllib.request.Request(
        OVERPASS,
        data=urllib.parse.urlencode({"data": query}).encode(),
        headers={"User-Agent": "family-3d-printing-project/1.0"},
    )
    with urllib.request.urlopen(req, timeout=90) as r:
        return json.load(r)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bbox", required=True,
                    help="south,west,north,east (from openstreetmap.org Export)")
    ap.add_argument("--width-mm", type=float, default=120,
                    help="printed size of the longer side (default 120mm)")
    ap.add_argument("--base", type=float, default=2.4,
                    help="base plate thickness (default 2.4mm)")
    ap.add_argument("--road-raise", type=float, default=0.8,
                    help="how far roads stand above the plate (default 0.8mm)")
    args = ap.parse_args()

    bbox = [float(x) for x in args.bbox.split(",")]
    south, west, north, east = bbox

    print("Downloading streets from OpenStreetMap...", file=sys.stderr)
    data = fetch(bbox)
    ways = [e for e in data["elements"]
            if e["type"] == "way" and "geometry" in e]

    lat0 = math.radians((south + north) / 2)
    w_m = (east - west) * 111_320.0 * math.cos(lat0)
    d_m = (north - south) * 111_320.0
    mm = args.width_mm / max(w_m, d_m)          # mm per real meter
    plate_w, plate_d = w_m * mm, d_m * mm

    def to_mm(lon, lat):
        return ((lon - west) * 111_320.0 * math.cos(lat0) * mm,
                (lat - south) * 111_320.0 * mm)

    out = sys.stdout
    out.write("// Generated by streets-to-scad.py — real OpenStreetMap streets!\n")
    out.write(f"// bbox: {args.bbox}\n")
    out.write(f"// plate: {plate_w:.0f} x {plate_d:.0f} mm\n\n")
    out.write(f"plate_w = {plate_w:.2f}; plate_d = {plate_d:.2f};\n")
    out.write(f"base = {args.base}; raise = {args.road_raise};\n\n")
    out.write("cube([plate_w, plate_d, base]);\n\n")
    out.write("// every road segment = hull of two circles, extruded\n")
    out.write("module seg(x1, y1, x2, y2, r)\n")
    out.write("    translate([0, 0, base]) linear_extrude(raise)\n")
    out.write("        hull() { translate([x1, y1]) circle(r, $fn = 12);\n")
    out.write("                 translate([x2, y2]) circle(r, $fn = 12); }\n\n")

    n_segs = 0
    for way in ways:
        cls = way.get("tags", {}).get("highway", "residential")
        # road half-width in mm: class width in real meters, at map scale,
        # but never thinner than 0.5mm so it actually prints
        r = max(0.5, ROAD_CLASSES.get(cls, 2.0) * mm)
        pts = [to_mm(p["lon"], p["lat"]) for p in way["geometry"]]
        # clamp to the plate so roads don't stick out past the edge
        pts = [(min(max(x, 0), plate_w), min(max(y, 0), plate_d))
               for x, y in pts]
        name = way.get("tags", {}).get("name", "")
        if name:
            out.write(f"// {name}\n")
        for (x1, y1), (x2, y2) in zip(pts, pts[1:]):
            if (x1, y1) != (x2, y2):
                out.write(f"seg({x1:.2f}, {y1:.2f}, {x2:.2f}, {y2:.2f}, {r:.2f});\n")
                n_segs += 1

    print(f"Done: {len(ways)} roads, {n_segs} segments, "
          f"plate {plate_w:.0f} x {plate_d:.0f} mm.", file=sys.stderr)
    if n_segs > 4000:
        print("WARNING: that's a lot of segments — OpenSCAD's F6 render "
              "will be slow. Shrink the bbox for a snappier model.",
              file=sys.stderr)


if __name__ == "__main__":
    main()
