#!/usr/bin/env python3
"""
TERRAIN-TO-SCAD — print the actual shape of the land.

Downloads real elevation data for any spot on Earth and writes:
  1. terrain.dat  — a grid of heights (in mm, ready to print)
  2. an OpenSCAD file (stdout) that turns the grid into a solid model
     using surface() — OpenSCAD's built-in heightmap tool.

Uses only the Python standard library — nothing to install.
Elevation data: Open-Elevation API (free, no key). If it's down, try
again later or use https://touchterrain.geol.iastate.edu in the browser.

Usage:
  1. Find a bbox at https://www.openstreetmap.org -> Export
     (mountains and river valleys are WAY more fun than flat suburbs)
  2. python3 terrain-to-scad.py --bbox 44.25,-71.35,44.30,-71.28 \
         --out-dat terrain.dat > mountain.scad
     (that example is Mount Washington)
  3. Open mountain.scad in OpenSCAD (keep terrain.dat next to it),
     F6, export STL, print.

Tips:
  * --z-exaggerate 2 makes gentle hills look dramatic (map makers
    really do this — it's called vertical exaggeration).
  * --samples 80 = more detail but slower download and bigger STL.
"""

import argparse
import json
import math
import sys
import urllib.request

API = "https://api.open-elevation.com/api/v1/lookup"
CHUNK = 400  # points per request — polite to the free API


def fetch_elevations(points):
    """points: list of (lat, lon) -> list of elevations in meters."""
    out = []
    for i in range(0, len(points), CHUNK):
        chunk = points[i:i + CHUNK]
        body = json.dumps({
            "locations": [{"latitude": la, "longitude": lo} for la, lo in chunk]
        }).encode()
        req = urllib.request.Request(
            API, data=body,
            headers={"Content-Type": "application/json",
                     "User-Agent": "family-3d-printing-project/1.0"})
        with urllib.request.urlopen(req, timeout=120) as r:
            data = json.load(r)
        out.extend(p["elevation"] for p in data["results"])
        done = min(i + CHUNK, len(points))
        print(f"  elevation points: {done}/{len(points)}", file=sys.stderr)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bbox", required=True,
                    help="south,west,north,east (from openstreetmap.org Export)")
    ap.add_argument("--samples", type=int, default=60,
                    help="grid resolution across the longer side (default 60)")
    ap.add_argument("--width-mm", type=float, default=140,
                    help="printed size of the longer side (default 140mm)")
    ap.add_argument("--z-exaggerate", type=float, default=1.5,
                    help="stretch heights by this factor (default 1.5)")
    ap.add_argument("--base", type=float, default=3,
                    help="minimum model thickness in mm (default 3)")
    ap.add_argument("--out-dat", default="terrain.dat",
                    help="heightmap file to write (default terrain.dat)")
    args = ap.parse_args()

    south, west, north, east = [float(x) for x in args.bbox.split(",")]

    # real-world size of the box, in meters
    lat0 = math.radians((south + north) / 2)
    w_m = (east - west) * 111_320.0 * math.cos(lat0)
    d_m = (north - south) * 111_320.0

    # grid: sample the longer side `samples` times, keep cells square
    if w_m >= d_m:
        nx, ny = args.samples, max(8, round(args.samples * d_m / w_m))
    else:
        ny, nx = args.samples, max(8, round(args.samples * w_m / d_m))

    pts = [(south + (north - south) * iy / (ny - 1),
            west + (east - west) * ix / (nx - 1))
           for iy in range(ny) for ix in range(nx)]

    print(f"Downloading {len(pts)} elevation points...", file=sys.stderr)
    elev = fetch_elevations(pts)

    lo, hi = min(elev), max(elev)
    relief = max(hi - lo, 1.0)
    mm_per_m = args.width_mm / max(w_m, d_m)   # true scale
    print(f"Terrain: {lo:.0f}m to {hi:.0f}m ({relief:.0f}m of relief), "
          f"scale 1:{1000 / mm_per_m:.0f}", file=sys.stderr)

    # heights in printed mm: base thickness + true-scale relief, exaggerated
    def height(e):
        return args.base + (e - lo) * mm_per_m * args.z_exaggerate

    with open(args.out_dat, "w") as f:
        for iy in range(ny - 1, -1, -1):          # surface() reads top row first
            row = [f"{height(elev[iy * nx + ix]):.2f}" for ix in range(nx)]
            f.write(" ".join(row) + "\n")

    cell = args.width_mm / (max(nx, ny) - 1)
    out = sys.stdout
    out.write("// Generated by terrain-to-scad.py — real Earth elevation!\n")
    out.write(f"// bbox {args.bbox}  relief {relief:.0f}m  "
              f"exaggeration x{args.z_exaggerate:g}\n")
    out.write(f"// print size ~{cell*(nx-1):.0f} x {cell*(ny-1):.0f} mm\n\n")
    out.write(f"scale([{cell:.3f}, {cell:.3f}, 1])\n")
    out.write(f"    surface(file = \"{args.out_dat}\", convexity = 5);\n")
    print(f"Done. Wrote {args.out_dat} ({nx}x{ny}); "
          "open the .scad next to it.", file=sys.stderr)


if __name__ == "__main__":
    main()
